---
title: "Urban_GIS_project"
author: "Jeff Kropelnicki"
date: "2/18/2017"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(readr)
library(VIM)
library(lattice)
library(gridExtra)
```


Load Data
```{r, message=FALSE}
#Foreclosure data
foreclosures <- read_csv("//Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/foreclosures..csv") 

#Parcel polygons from http://www.hennepin.us/your-government/open-government/gis-open-data parcels opened in ArcGIS then exported to .csv. 
parcels <- read_csv("/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/parcel.csv")

#Parcel points from http://www.hennepin.us/your-government/open-government/gis-open-data same as above. 
parcel_point <- read_csv("/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/parcel_points.csv")
```


clean data
```{r}
parcels <- separate(parcels, col = PID, into = c("county", "PID_1"), sep = "-") #sepirates PID 

parcels <- unite(parcels, FULLADDRESS, BLDG_NUM, STREETNAME, sep = " ", remove = TRUE) #Combining BLDG_NUM, STREETNAME to FULLADDRESS. 

foreclosures$FULLADDRESS <- tolower(foreclosures$FULLADDRESS) #Makes FULLADDRESS to lowercase for a join with parcels 

parcels$FULLADDRESS <- tolower(parcels$FULLADDRESS) #Makes FULLADDRESS to lowercase for join with foreclosures

parcels$SALE_DATE <- mdy_hms(parcels$SALE_DATE) #Sets date to hours minutes sec. 

foreclosures$SHERIFFSAL <- mdy_hms(foreclosures$SHERIFFSAL) #Sets date to hours minutes sec.

foreclosures_work <- foreclosures %>% separate(col = SHERIFFSAL,into = c("sheriffsal_year", "sheriffsal_month", "sheriffsal_day"), sep = "-") #separate SALE_DATE to year, month and day. 

parcels_clean <- select(parcels, OBJECTID, COUNTY_ID, PIN, FULLADDRESS, CITY, ZIP, OWNER_NAME, HOMESTEAD, TOTAL_TAX, YEAR_BUILT, SALE_DATE, SALE_VALUE, SCHOOL_DST, Shape_Length, Shape_Area, county, PID_1, USE1_DESC)
names(parcels)

foreclosures_clean <- select(foreclosures_work, OBJECTID, FULLADDRESS, CITY, sheriffsal_year, sheriffsal_month, sheriffsal_day, FCLS_YR, LIENTYPE, REDEMPEXP, MORTGAGORL, MORGTAGORF, CURRENTMORT, FIRSTBIDAM, FINALBIDAM, LAWFIRMATT, POINT_X, POINT_Y)

foreclosures_clean$REDEMPEXP <- mdy_hms(foreclosures_clean$REDEMPEXP)

```   
   
Join data
```{r}
parcel_foreclosures <- merge(x = parcels, y = foreclosures_work, by = "FULLADDRESS", all.x = TRUE)

#left join
Join <- parcels_clean %>% left_join(foreclosures_clean, by = c("FULLADDRESS"))

#Clean for left join
parcel_foreclosures_polygon <- select(join, OBJECTID = OBJECTID.x, PIN, FULLADDRESS, CITY = CITY.x, ZIP, OWNER_NAME, HOMESTEAD, TOTAL_TAX, YEAR_BUILT, SALE_DATE, SALE_VALUE, SCHOOL_DST, Shape_Length, Shape_Area, county, sheriffsal_year, sheriffsal_month, sheriffsal_day, FCLS_YR, FIRSTBIDAM, FINALBIDAM, POINT_X, POINT_Y, USE1_DESC)

#Right join
parcel_foreclosures_join <- parcels_clean %>% right_join(foreclosures_clean, by = c("FULLADDRESS"))

#Clean for right join
parcel_foreclosures_join <- parcel_foreclosures_join %>% select(OBJECTID = OBJECTID.x, PIN, FULLADDRESS,YEAR_BUILT,SALE_DATE, SALE_VALUE, sheriffsal_year, sheriffsal_month, sheriffsal_day, FIRSTBIDAM, SCHOOL_DST, FCLS_YR, USE1_DESC, FINALBIDAM, CITY = CITY.x, ZIP, OWNER_NAME, HOMESTEAD, TOTAL_TAX, county, POINT_X, POINT_Y, Shape_Length, Shape_Area)

parcel_foreclosures_join <- parcel_foreclosures_join %>% unite(sheriffsal, sheriffsal_year, sheriffsal_month, sheriffsal_day, sep = "-", remove = FALSE)

parcel_foreclosures_join %>% mutate(new_cal = SALE_DATE > sheriffsal)

```  

Cleaning full Brooklyn park parcel point data
```{r}
parcel_point <- unite(parcel_point, FULLADDRESS, BLDG_NUM, STREETNAME, sep = " ", remove = TRUE)

parcel_point$FULLADDRESS <- tolower(parcel_point$FULLADDRESS)

parcel_point$SALE_DATE <- mdy_hms(parcel_point$SALE_DATE)

parcel_point <- select(parcel_point, OBJECTID, COUNTY_ID, PIN, FULLADDRESS, CITY, ZIP, PLAT_NAME, USE1_DESC, OWNER_NAME, TAX_NAME, HOMESTEAD, YEAR_BUILT, SALE_DATE, SALE_VALUE, SCHOOL_DST, POINT_X, POINT_Y)
```

Investigate data 
```{r}
unique(foreclosures_work$LIENTYPE) #Prints unique varibles in the LIENTYPE column. Mortgage, Assessment, Judgment, Association, Execution, Assocation. 

#Homes that have been through more then one foreclosures, LIENTYPE = Mortgage and removes bad point 48 address pending. 
more_then_one_foreclosure <- foreclosures_work %>% filter(LIENTYPE == "Mortgage") %>% group_by(FULLADDRESS) %>% summarise(records = n()) %>% arrange(desc(records)) %>% filter(records > 1) %>% filter(FULLADDRESS != "48 address pending") 

#want to see info about this home on its own. 
row <- foreclosures_work[which(foreclosures_work$FULLADDRESS =="russell ave n"),] 

#Looking for a count of homes that have been through more then one foreclosures.
more_then_one_foreclosure_count <- foreclosures_work %>% group_by(FULLADDRESS) %>% summarise(number_of_foreclosures = n()) %>% count(number_of_foreclosures >= 2) #Looking for a count of homes that have been through more then one foreclosures.


#Count the number of foreclosures for each day of the month. 
days <- foreclosures_work %>% group_by(sheriffsal_day) %>% summarise(what_day = n()) %>% arrange(sheriffsal_day)

#Count the number of foreclosures for each month of the year. 
month <- foreclosures_work %>% group_by(sheriffsal_month) %>% summarise(what_month = n()) %>% arrange(sheriffsal_month) 

#Count the number of foreclosures for each year.
year <- foreclosures_work %>% group_by(FCLS_YR) %>% summarise(what_year = n()) %>% arrange(FCLS_YR)


#Plot the number of foreclosures for each day of the month. 
plot(days, type="l", xlab = "Day Of The Month", ylab = "Number of Foreclosures", main = "Total On Each Day Of The Month")

#Plot the number of foreclosures for each month of the year. 
plot(year, type="l", xlab = "Year", ylab = "Number of Foreclosures", main = "Total Foreclosures Over 2005 to 2016")

#Plot the number of foreclosures for each year. 
plot(month, type="l", xlab = "month", ylab = "Number of Foreclosures", main = "Total Foreclosures In All Months")


```


Investigate data Number Of Foreclosures Per Month By Year   
```{r}
#Count of the number of foreclosures by month and year. 
number_per_month_and_year <- foreclosures_work %>% group_by(sheriffsal_year, sheriffsal_month) %>% summarize(count = n())

#Point plot of number of foreclosures by month per year with legend. 
plot(count ~ sheriffsal_month + sheriffsal_year, data = number_per_month_and_year, main = "Number Of Foreclosures Per Month By Year", ylab = "Number Of Foreclosures", xlab = "Year", col = c("red", "blue", "cyan1", "chocolate1", "blueviolet", "darkorchid4", "darkslategray", "gray0", "deeppink4", "lawngreen", "cornflowerblue", "bisque4"), cex = 4, pch = 21)
legend("topright", legend = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Oug", "Sep", "Oct", "Nov", "Dec"), fill = c("red", "blue", "cyan1", "chocolate1", "blueviolet", "darkorchid4", "darkslategray", "gray0", "deeppink4", "lawngreen", "cornflowerblue", "bisque4" ), bty = "n")

#Boxplot using the lattice library. 
bwplot(count ~ sheriffsal_year, data = number_per_month_and_year, main = "Number Of Foreclosures Per Month By Year", ylab = "Number Of Foreclosures", xlab = "Year")

#Boxplot with base R. 
boxplot(count ~ sheriffsal_year, data = number_per_month_and_year, main = "Number Of Foreclosures Per Month By Year", ylab = "Number Of Foreclosures", xlab = "Year", col = c("cyan1"))



#This code will export this plot to any .jpg file. 
#jpeg('/Users/jeffkropelnicki/Desktop/test.jpg', quality = 500, width = 640, height = 640, pointsize = 14)
#boxplot(count ~ sheriffsal_year, data = number_per_month_and_year, main = "Number Of Foreclosures Per Month By Year", ylab = "Number Of Foreclosures", xlab = "Year", col = c("cyan1"), cex = 1, pch = 21)
#dev.off()

```   
   
Looking at the historgam there is something going on in 2009-2010. The mean went up in 2010 over 2009.
```{r}
#looking at the plots in the boxplot for 2008, 2009 and 2010 I want to see what is happening in #2009 to get a better understanding about that makes 2009 different. 
look_2009 <- foreclosures_work %>% group_by(sheriffsal_year, sheriffsal_month) %>% filter(sheriffsal_year == "2009" | sheriffsal_year == "2010") %>% summarise(count = n()) 

look_2009 <- foreclosures_work %>% group_by(sheriffsal_year, sheriffsal_month) %>% filter(sheriffsal_year == "2009" | sheriffsal_year == "2010") %>% summarise(count = n())


boxplot(count~ sheriffsal_year, data = look_2009)
```


Writing to csv
```{r}
write.csv(parcel_point, file = "/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/parcel_point.csv")

write.csv(foreclosures_clean, file = "/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/foreclosures_data_from_Brooklyn_park_clean.csv")

write.csv(parcel_foreclosures_polygon, file = "/Users/jeffkropelnicki/Desktop/parcel_foreclosures_polygon.csv")

write.csv(month, file = "/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/month.csv")
write.csv(day, file = "/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/day.csv")
write.csv(year, file = "/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/year.csv")

write.csv(parcel_foreclosures_point, file = "/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/parcel_foreclosures_point.csv")

write.csv(foreclosures_clean, file = "/Users/jeffkropelnicki/Desktop/GIS5564_Urban_GIS/Project/foreclosures_data_from_Brooklyn_park_clean.csv")

write.csv(number_per_month_and_year, file = "/Users/jeffkropelnicki/Desktop/year_and_month.csv")

write.csv(more_then_one_foreclosure, file = "/Users/jeffkropelnicki/Desktop/More_then_onces_mortgage.csv")
``` 

Look at data based on when the homes were built.   
```{r}
Residential <- c("Vacant Land - Residential", "Residential", "Townhouse", "Residential-Zero Lot Line-DB", "Disabled", "Double Bungalow", "Resd'l Misc & Bed & Breakfast", "Blind", "Condominium", "Disabled Joint Tenancy", "Residential Lakeshore", "Apartment", "Seasonal Residential Rec.", "Triplex", "Housing - Low Income > 3 Units")

parcels$USE1_DESC[parcels$USE1_DESC %in% Residential] <- "Residential"

foreclosure <- foreclosures_work %>% select(FULLADDRESS, sheriffsal_year, FIRSTBIDAM)


Join_Year_built <- parcels %>% right_join(foreclosure, by = c("FULLADDRESS")) %>% select(FULLADDRESS, USE1_DESC, YEAR_BUILT, sheriffsal_year) %>% filter(sheriffsal_year > YEAR_BUILT)

Join_Year_built$sheriffsal_year <- as.integer(Join_Year_built$sheriffsal_year)

Join_Year_built <- Join_Year_built %>% mutate(owned = sheriffsal_year - YEAR_BUILT) 

mean(Join$owned, na.rm = TRUE) #avg number of years a home was built before a foreclosure 28.81 years

homes_greater_1990 <- Join_Year_built %>% filter(YEAR_BUILT >= 1990)
homes_less_1990 <- Join_Year_built %>% filter(YEAR_BUILT < 1990)

homes_after_1990 <- Join_Year_built %>% filter(YEAR_BUILT >= 1990) %>% group_by(YEAR_BUILT) %>%  summarise(Number_of_Foreclosures = n()) 

homes_before_1990 <- Join_Year_built %>% filter(YEAR_BUILT < 1990 & YEAR_BUILT > 1967) %>% group_by(YEAR_BUILT) %>% summarise(Number_of_Foreclosures = n())

mean(homes_after_1990$count) # ave number of foreclosures per year = 55.2381
mean(homes_before_1990$count) # ave number of foreclosures per year = 91.9

max(homes_after_1990$count) # most in one year 169 year 2005
max(homes_before_1990$count) #most in one year 351 year 1978

summary(homes_after_1990)

1160/5426 #percent of total 0.21
3719/5426 #percent of total 0.69

homes_per_year <- homes_built %>% summarise(count = n()) 

homes_1966 <- parcels %>% select(YEAR_BUILT) %>% filter(YEAR_BUILT <= 1965 & YEAR_BUILT >= 1940) %>% group_by(YEAR_BUILT) %>%  summarise(Number_of_Homes_built = n())

homes_1968_1989 <- parcels %>% select(YEAR_BUILT) %>% filter(YEAR_BUILT <= 1991 & YEAR_BUILT >= 1966) %>% group_by(YEAR_BUILT) %>%  summarise(Number_of_Homes_built = n())

homes_1990 <- parcels %>% select(YEAR_BUILT) %>% filter(YEAR_BUILT >= 1992) %>% group_by(YEAR_BUILT) %>%  summarise(Number_of_Homes_built = n())

median(homes_per_year_after_1950$count)
mean(homes_per_year_after_1950$count) # Avg number of homes built after 1950 338
```   
   


Want to see what types of home were in foreclosure 
```{r}
home_type <- parcels %>% select(FULLADDRESS, USE1_DESC, YEAR_BUILT) %>% filter(YEAR_BUILT > 1) 

Join <- home_type %>% right_join(foreclosure, by  = c("FULLADDRESS"))

house_type <- Join %>% group_by(USE1_DESC ) %>% summarise(count = n()) %>% filter(USE1_DESC != "NA") %>% filter(USE1_DESC != "Commercial") %>% filter(USE1_DESC != "Industrial") %>% arrange(desc(count)) %>% rename(Home_Type = USE1_DESC) %>% rbind(., data.frame(Home_Type="Total", count=sum(.$count, na.rm=T)))

town_home <- Join %>% filter(USE1_DESC == "Townhouse")

homes_built <-  parcels %>% select(FULLADDRESS, USE1_DESC, YEAR_BUILT, Shape_Length, Shape_Area) %>% group_by(YEAR_BUILT) %>% filter(USE1_DESC == "Residential") %>% filter(YEAR_BUILT > 1) 
```


